### ISSUE TITLE
Doing '[]giverole \' has no output

### ISSUE THREAD

**Issue by AquaXV** [YilianSource/brackeys-bot#133] opened 2018-12-16 20:49 UTC
When users do '[]giverole \' the bot outputs nothing, when users do '[]giverole \\' it displays the help message for giverole

**Comment by MetalBreaker** [comment] 2019-01-09 18:56
Discord.NET bug, I believe. '\' is an escape character, and the command fails.

**Comment by YilianSource** [comment] 2019-01-13 22:40
Indeed, it's Discord.NET's parsing that is failing here. To be more exact: 
`ParseFailed: "Input text may not end on an incomplete escape."`.

If you feel like we should automatically trim incomplete escape sequences, feel free to suggest that!

**Comment by CodeMyst** [comment] 2019-01-13 23:01
Looks like this changed. `[]giverole` outputs all the roles and teams and `[]giverole \` doesn't. It would be nice if `[]giverole \` also outputted all the roles and teams.

**Comment by YilianSource** [comment] 2019-01-14 09:23
Looks like this can't really be fixed since that is expected behaviour from Discord.NET. We can't access a message's content without explicitly modifying it, therefore we can't "ignore" the incomplete escape sequence.

**Comment by CodeMyst** [comment] 2019-01-14 10:47
I see. It's not a big deal then. Can we close this then?

**Closed** 2019-01-14 17:38 UTC
Labels: bug, question
